### ISSUE TITLE
README and repository description

### ISSUE THREAD

**Issue by fabiand** [kubevirt-incubator/kubevirt-ansible#1]
Please add some human readable decriptions to tell the user what this repo is about.

**Comment by lukas-bednar** [comment]
I don't have a permission to modify description of repository, but I suggest something like
```
Set of Ansible roles & playbooks for KubeVirt deployment
```

**Comment by cynepco3hahue** [comment]
@fabiand Can you please edit the repository description?

**Comment by fabiand** [comment]
Done
