### ISSUE TITLE
Add content based on consolidation of Petr's & Artyom's work

### ISSUE THREAD

**Issue by lukas-bednar** [kubevirt-incubator/kubevirt-ansible#2]
Merge following two repositories

https://github.com/petrkotas/openshift-env
https://github.com/cynepco3hahue/kubevirt-ansible

As a result this repository contains Ansible roles & playbooks to deploy KubeVirt on
* stand alone K8S
* OpenShift deployment

cc @cynepco3hahue @petrkotas 

We need to have some discussion how to proceed with merging process.

**Comment by cynepco3hahue** [comment]
@petrkotas @lukas-bednar I can see that Petr deployment concentrates at most on the `vagrant`, so maybe we can add roles from my repository, `Vagrantfile` from the Petr repository and adapt this Vagrantfile to use my roles?

**Comment by cynepco3hahue** [comment]
Also, we can take my `README.md` and add a section for `vagrant` deployment.

**Comment by lukas-bednar** [comment]
@cynepco3hahue ok, for start think you can push your changes here from your old repo ...

```bash
cd cynepco3hahue/kubevirt-ansible
git remote add kubevirt-incubator git@github.com:kubevirt-incubator/kubevirt-ansible.git
git push -f kubevirt-incubator master
```

or you can consider to transfer ownership of your repo, to kubevirt-incubator.

**Comment by petrkotas** [comment]
@cynepco3hahue Yes this was exactly my thinking. That we adapt your roles and use my vagrant :).

Best would be start with your repository as @lukas-bednar wrote and than add my changes.

I can do that so we have a starting point.

**Comment by cynepco3hahue** [comment]
@petrkotas @lukas-bednar I added #4, so if it looks fine we can merge it and go on with Petr repository.

**Comment by petrkotas** [comment]
I have taken look at #4 I can start on that.

**Comment by cynepco3hahue** [comment]
@petrkotas @lukas-bednar I think we added all base content, so I will close this one.
