### ISSUE TITLE
The deploy playbooks doesn't populate KubeVirt pods

### ISSUE THREAD

**Issue by lukas-bednar** [kubevirt-incubator/kubevirt-ansible#6]
After running deployment playbook I would expect to see populated KubeVirt's pods, for virtualization

on behalf of @cynepco3hahue 
> @lukas-bednar this part is problematic currently because we need to configure security context for libvirt and virt-handlers daemon sets, patch that must fix it kubevirt/kubevirt#418
In additional openshift does not support CustomResourseDefinition, with this patch we will get rid of it
kubevirt/kubevirt#355

copied from https://github.com/cynepco3hahue/kubevirt-ansible/issues/6

**Comment by fabiand** [comment]
@lukas-bednar @cynepco3hahue is there an issue tracking the work needed to be done for the security contexts?

**Comment by lukas-bednar** [comment]
@fabiand Only things I am aware of are that two PRs mentioned in description.

From my point of view, we are blocked only in OSP part because of CRD.

On K8S-only deployment, population of KubeVirt pods shouldn't be problem. We just need to load files under manifests directory as a part of our Ansible playbook.

**Comment by gbenhaim** [comment]
fixed https://github.com/kubevirt-incubator/kubevirt-ansible/pull/37
